### ISSUE TITLE
Can't import DiscordBotConstruct due to missing TypeScript file

### ISSUE THREAD

**Issue by timbru31** [GEMISIS/discord-bot-cdk-construct#1]
Hi,

awesome project, this is exactly what I am looking for.
However, either I have misunderstood the instructions or there is a bug in the code.

I've gone ahead and made a new CDK app where I installed and import this construct: `new DiscordBotConstruct(this, "test", { commandsLambdaFunction: handler });`

However, `cdk` fails with the following error:
> Cannot find entry file at [...]/node_modules/discord-bot-cdk-construct/dist/functions/DiscordBotFunction.ts

I suspect this is because [here](https://github.com/GEMISIS/discord-bot-cdk-construct/blob/main/src/constructs/DiscordBotConstruct.ts#L40) the function is referenced as a TypeScript file, but the published npm package contains the transpiled JS file.

---

Furthermore, it would be awesome if you could extend your example a bit more, I've had a hard time understanding whether I should use/import your construct or fork this repo to build upon it. :)

**Comment by GEMISIS** [comment]
Just updated to [version 0.1.7 on npm](https://www.npmjs.com/package/discord-bot-cdk-construct), which I've now properly tested end-to-end and includes better usage documentation. You can see a full example of it in use at [https://github.com/RGB-Schemes/oculus-start-bot](https://github.com/RGB-Schemes/oculus-start-bot) (the main files to look at are in the readme for [this](https://github.com/GEMISIS/discord-bot-cdk-construct/) repo).
