### ISSUE TITLE
NODEJS_14_x no longer supported

### ISSUE THREAD

**Issue by gergnz** [GEMISIS/discord-bot-cdk-construct#10]
NodeJS in lambda is deprecated.

https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html

https://github.com/GEMISIS/discord-bot-cdk-construct/blob/0d262e2809a298a10af594a1033077d3a08e1b0a/src/constructs/DiscordBotConstruct.ts#L40

Please update to NODEJS_18_x

**Comment by GEMISIS** [comment]
Appreciate you filing this, will work to get this updated!
