### ISSUE TITLE
Passed in command lambda should be allowed to access secrets

### ISSUE THREAD

**Issue by timbru31** [GEMISIS/discord-bot-cdk-construct#2]
In order to have the example working the passed command lambda should receive access to the Discord secrets. I've added these two statements in the `DiscordBotConstruct.ts`

```ts
    props.commandsLambdaFunction.addEnvironment("DISCORD_BOT_API_KEY_NAME", this.discordAPISecrets.secretName);
    this.discordAPISecrets.grantRead(props.commandsLambdaFunction);
```

**Comment by GEMISIS** [comment]
Appreciate you reporting this! Went ahead and fix this 😄
