### ISSUE TITLE
npm install for v0.1.8 still comes with oculus-start reference

### ISSUE THREAD

**Issue by FilipeAleixo** [GEMISIS/discord-bot-cdk-construct#6]
I see that you've removed the oculus-start name reference in this commit https://github.com/GEMISIS/discord-bot-cdk-construct/commit/b0da96f71bc6d9589c5834b95ecee9c9dd69a488, but npm install for version 0.1.8 is still not updated to reflect that. Could you update?

**Comment by GEMISIS** [comment]
Fixed as a part of upgrading to CDK 2.0 for issue #7.
